/*
 * ADC.c
 *
 * Created: 25/11/41 06:42:12 ص
 *  Author: ABDULLAH 01
 */ 

#include "ADC.h"


void ADC_INIT(void)
{
#if VOLTAGE_REFRENCE   ==    ADC_VREF_AVCC

SET_BIT(ADMUX,6);
CLR_BIT(ADMUX,7);

#elif VOLTAGE_REFRENCE   ==     ADC_VREF_INTERNAL_AREF 

SET_BIT(ADMUX,6);
SET_BIT(ADMUX,7);

#elif VOLTAGE_REFRENCE   ==     ADC_VREF_INTERNAL_TURNED_OFF

CLR_BIT(ADMUX,6);
CLR_BIT(ADMUX,7);

#endif

#if ADC_CHANNEL       ==   ADC_CHANNEL_0

CLR_BIT(ADMUX,0);

#elif ADC_CHANNEL       ==   ADC_CHANNEL_1

SET_BIT(ADMUX,0);

#elif ADC_CHANNEL     ==   ADC_CHANNEL_2

SET_BIT(ADMUX,1);

#elif ADC_CHANNEL       ==   ADC_CHANNEL_3

SET_BIT(ADMUX,0);
SET_BIT(ADMUX,1);

#elif ADC_CHANNEL       ==   ADC_CHANNEL_4

CLR_BIT(ADMUX,0);
CLR_BIT(ADMUX,1);
SET_BIT(ADMUX,2);

#elif ADC_CHANNEL       ==   ADC_CHANNEL_5

SET_BIT(ADMUX,0);
CLR_BIT(ADMUX,1);
SET_BIT(ADMUX,2);

#elif ADC_CHANNEL       ==   ADC_CHANNEL_6

CLR_BIT(ADMUX,0);
SET_BIT(ADMUX,1);
SET_BIT(ADMUX,2);

#elif ADC_CHANNEL       ==   ADC_CHANNEL_7

SET_BIT(ADMUX,0);
SET_BIT(ADMUX,1);
SET_BIT(ADMUX,2);

#endif

#if VOLTAGE_ADJUCENT     ==  ADC_RIGHT_ADJUST

CLR_BIT(ADMUX,5);

#elif VOLTAGE_ADJUCENT   ==  ADC_LEFT_ADJUST

SET_BIT(ADMUX,5);

#endif

#if ADC_CONVERSION_TRIGGER== ADC_AUTO_TRIGGER

SET_BIT(ADCSRA,5);

#endif

#if ADC_PRESCALER     ==     ADC_PRESEC_128

SET_BIT(ADCSRA,0);
SET_BIT(ADCSRA,1);
SET_BIT(ADCSRA,2);

#elif ADC_PRESCALER     ==     ADC_PRESEC_2

CLR_BIT(ADCSRA,0);
CLR_BIT(ADCSRA,1);
CLR_BIT(ADCSRA,2);

#elif ADC_PRESCALER     ==     ADC_PRESEC_2b

SET_BIT(ADCSRA,0);
CLR_BIT(ADCSRA,1);
CLR_BIT(ADCSRA,2);

#elif ADC_PRESCALER     ==     ADC_PRESEC_4

CLR_BIT(ADCSRA,0);
SET_BIT(ADCSRA,1);
CLR_BIT(ADCSRA,2);

#elif ADC_PRESCALER     ==     ADC_PRESEC_8

SET_BIT(ADCSRA,0);
SET_BIT(ADCSRA,1);
CLR_BIT(ADCSRA,2);

#elif ADC_PRESCALER     ==     ADC_PRESEC_16

CLR_BIT(ADCSRA,0);
CLR_BIT(ADCSRA,1);
SET_BIT(ADCSRA,2);

#elif ADC_PRESCALER     ==     ADC_PRESEC_32

SET_BIT(ADCSRA,0);
CLR_BIT(ADCSRA,1);
SET_BIT(ADCSRA,2);

#elif ADC_PRESCALER     ==     ADC_PRESEC_64

CLR_BIT(ADCSRA,0);
SET_BIT(ADCSRA,1);
SET_BIT(ADCSRA,2);

#endif

#if ADC_INTERRUPT_STATUS  == ADC_INTERRUPT_DISABLE

CLR_BIT(ADCSRA,3);

#elif ADC_INTERRUPT_STATUS  == ADC_INTERRUPT_ENABLE

SET_BIT(ADCSRA,3);
SET_BIT(SREG,7);

#endif

/* Enable ADC */

SET_BIT(ADCSRA,7);
}

void ADC_READ(uint16* value)
{
	uint16 Digital_value=0;
	
	SET_BIT(ADCSRA,6);
	
	#if ADC_INTERRUPT_STATUS  == ADC_INTERRUPT_DISABLE
	
	while (! GET_BIT(ADCSRA,4));
	
	Digital_value=ADC_ADJUST; //(ADCH << 2) | (ADCL >>6);
	
	*value=((Digital_value *500)/1024);
	
	#endif
	
}